### PR TITLE
Tile Class from Keiko's Group

### PR DESCRIPTION
**Pull request by kfujii12**
Implemented the Tile class

### CODE REVIEW

**Comment by nik-tripp** [comment]
I may not have a proper understanding of how we'll be using the function, but it appears to me that the toString() method is somewhat incomplete. Do we want to print out the surrounding bomb count of tiles which have not been revealed? Should we worry about cases where the tile is, itself, a bomb?

**Comment by kfujii12** [comment]
Just let me know how you all would like it formatted, and I can change it.

**Comment by nik-tripp** [comment]
We'll need to get back to you, I think. I'm probably going to get myself
fired with all the changes I keep informally proposing to Michael... I'll
try to keep my mouth shut 😁

On Tue, Dec 1, 2015 at 2:15 PM, kfujii12 notifications@github.com wrote:

> Just let me know how you all would like it formatted, and I can change it.
> 
> > On Nov 30, 2015, at 11:37 PM, Nik Tripp notifications@github.com
> > wrote:
> > 
> > I may not have a proper understanding of how we'll be using the
> > function, but it appears to me that the toString() method is somewhat
> > incomplete. Do we want to print out the surrounding bomb count of tiles
> > which have not been revealed? Should we worry about cases where the tile
> > is, itself, a bomb?
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MichaelH13/CSIS321MineSweeper/pull/1#issuecomment-161112878
> .

## 

_Nikolas Tripp_
_Junior at George Fox University_
_Computer Science Major_
_ntripp13@georgefox.edu ntripp13@georgefox.edu || (541) 315-1176_

**Comment by MichaelH13** [comment]
Make it work, that's all I care about. I'm pretty sure you don't have the
time to entirely restructure things.

On Tue, Dec 1, 2015 at 2:31 PM, Nik Tripp notifications@github.com wrote:

> We'll need to get back to you, I think. I'm probably going to get myself
> fired with all the changes I keep informally proposing to Michael... I'll
> try to keep my mouth shut 😁
> 
> On Tue, Dec 1, 2015 at 2:15 PM, kfujii12 notifications@github.com wrote:
> 
> > Just let me know how you all would like it formatted, and I can change
> > it.
> > 
> > > On Nov 30, 2015, at 11:37 PM, Nik Tripp notifications@github.com
> > > wrote:
> > > 
> > > I may not have a proper understanding of how we'll be using the
> > > function, but it appears to me that the toString() method is somewhat
> > > incomplete. Do we want to print out the surrounding bomb count of tiles
> > > which have not been revealed? Should we worry about cases where the tile
> > > is, itself, a bomb?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/MichaelH13/CSIS321MineSweeper/pull/1#issuecomment-161112878
> > 
> > .
> 
> ## 
> 
> _Nikolas Tripp_
> _Junior at George Fox University_
> _Computer Science Major_
> _ntripp13@georgefox.edu ntripp13@georgefox.edu || (541) 315-1176_
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MichaelH13/CSIS321MineSweeper/pull/1#issuecomment-161117284
> .

## 

Michael Higgins
George Fox University
Computer Science
​ Senior
www.linkedin.com/in/michaelhiggins13

**Comment by kfujii12** [comment]
So if it's a bomb, do you want me to just print BOMB or something?

**Comment by sluo14** [comment]
I'm about to finish the Field class, but I'm still not sure what I should
do with the public void revealTile(Tile t) method. Here's what I have for
now:

   public void revealTile(Tile t)

   {

```
  if (! t.isRevealed())

  {

     if (t.isBomb())

     {

        System.out.println("You hit a bomb. You lost. ");

     }

     else

     {

        // have no idea what I should code in this part...

     }

  }
```

   }

**Comment by MichaelH13** [comment]
From a team discussion today:

Exclamation point! :)

Michael Higgins
George Fox University
Computer Science Senior
www.linkedin.com/in/michaelhiggins13

On Dec 1, 2015, at 9:30 PM, kfujii12 notifications@github.com wrote:

So if it's a bomb, do you want me to just print BOMB or something?

**Comment by kfujii12** [comment]
Just did a pull request with the change. I think I downloaded the repo
funny the first time, cause it won't let me do a push. But oh well. There's
a pull request waiting for you. :)

_Keiko Fujii_
_Senior at George Fox University_
_Computer Science major &&_ _Mathematics minor_
_kfujii12@georgefox.edu kfujii12@georgefox.edu_

**Pull request merged**
